version: "3.8"

services:

  postgresdb:
    image: postgres:14.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always

  postgresdb2:
    image: postgres:14.4
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: database2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always

  mysqldb:
    image: mysql:8.2
    ports:
      - "3366:3306"
    restart: always
    environment:
      MYSQL_DATABASE: database3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
